# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atualizar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 425)
        MainWindow.setStyleSheet("background-color: pink;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbPreco = QtWidgets.QLabel(self.centralwidget)
        self.lbPreco.setGeometry(QtCore.QRect(50, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbPreco.setFont(font)
        self.lbPreco.setObjectName("lbPreco")
        self.lbCategoria = QtWidgets.QLabel(self.centralwidget)
        self.lbCategoria.setGeometry(QtCore.QRect(20, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbCategoria.setFont(font)
        self.lbCategoria.setObjectName("lbCategoria")
        self.lbQuantidade = QtWidgets.QLabel(self.centralwidget)
        self.lbQuantidade.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbQuantidade.setFont(font)
        self.lbQuantidade.setObjectName("lbQuantidade")
        self.btnDeletar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeletar.setGeometry(QtCore.QRect(210, 320, 111, 61))
        self.btnDeletar.setStyleSheet("background-color: #DB6E79;\n"
"font-family: verdana;\n"
"border: 1px solid;\n"
"font-size: 11pt;")
        self.btnDeletar.setObjectName("btnDeletar")
        self.lbProduto = QtWidgets.QLabel(self.centralwidget)
        self.lbProduto.setGeometry(QtCore.QRect(30, 75, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbProduto.setFont(font)
        self.lbProduto.setObjectName("lbProduto")
        self.btnAtualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizar.setGeometry(QtCore.QRect(30, 320, 111, 61))
        self.btnAtualizar.setStyleSheet("background-color: #5AEB5B;\n"
"font-family: verdana;\n"
"border: 1px solid;\n"
"font-size: 11pt;")
        self.btnAtualizar.setObjectName("btnAtualizar")
        self.listCategoria = QtWidgets.QListWidget(self.centralwidget)
        self.listCategoria.setGeometry(QtCore.QRect(120, 190, 161, 31))
        self.listCategoria.setStyleSheet("background-color: white;\n"
"font-size:14pt;")
        self.listCategoria.setObjectName("listCategoria")
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listCategoria.addItem(item)
        self.lbTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lbTitulo.setGeometry(QtCore.QRect(110, 0, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setObjectName("lbTitulo")
        self.edtProduto = QtWidgets.QTextEdit(self.centralwidget)
        self.edtProduto.setGeometry(QtCore.QRect(110, 70, 221, 41))
        self.edtProduto.setStyleSheet("background-color: white;\n"
"font-size:14pt;")
        self.edtProduto.setObjectName("edtProduto")


        self.edtQuantidade = QtWidgets.QTextEdit(self.centralwidget)
        self.edtQuantidade.setGeometry(QtCore.QRect(120, 130, 61, 41))
        self.edtQuantidade.setStyleSheet("background-color: white;\n"
"font-size:14pt;")
        self.edtQuantidade.setObjectName("edtQuantidade")

        self.edtPreco = QtWidgets.QTextEdit(self.centralwidget)
        self.edtPreco.setGeometry(QtCore.QRect(120, 250, 81, 41))
        self.edtPreco.setStyleSheet("background-color: white;\n"
"font-size:14pt;")
        self.edtPreco.setObjectName("edtPreco")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbPreco.setText(_translate("MainWindow", "Preço:"))
        self.lbCategoria.setText(_translate("MainWindow", "Categoria:"))
        self.lbQuantidade.setText(_translate("MainWindow", "Quantidade:"))
        self.btnDeletar.setText(_translate("MainWindow", "Deletar"))
        self.lbProduto.setText(_translate("MainWindow", "Produto:"))
        self.btnAtualizar.setText(_translate("MainWindow", "Atualizar"))
        __sortingEnabled = self.listCategoria.isSortingEnabled()
        self.listCategoria.setSortingEnabled(False)
        item = self.listCategoria.item(0)
        item.setText(_translate("MainWindow", "Higiene"))
        item = self.listCategoria.item(1)
        item.setText(_translate("MainWindow", "Alimento"))
        item = self.listCategoria.item(2)
        item.setText(_translate("MainWindow", "frios e laticínios"))
        item = self.listCategoria.item(3)
        item.setText(_translate("MainWindow", "Brinquedo"))
        item = self.listCategoria.item(4)
        item.setText(_translate("MainWindow", "Enlatados"))
        item = self.listCategoria.item(5)
        item.setText(_translate("MainWindow", "Bebidas"))
        item = self.listCategoria.item(6)
        item.setText(_translate("MainWindow", "Açougue"))
        item = self.listCategoria.item(7)
        item.setText(_translate("MainWindow", "Outros"))
        self.listCategoria.setSortingEnabled(__sortingEnabled)
        self.lbTitulo.setText(_translate("MainWindow", "Alterar Produto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
