# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import CustomDialog
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from CustomDialog import CustomDialog
from CustomDialogEqualEmail import CustomDialogEqualEmail
from CustomEmailCreated import CustomEmailCreated
class Ui_CadastroWindow(object):

    def cadastrando(self):
        email = self.edt_email.text()
        senha = self.edt_senha.text()
        senhaConf = self.edt_senhaConf.text()

        conn = sqlite3.connect('login.db')
        cursor = conn.cursor()
        cursor.execute("SELECT email FROM cadastrados WHERE email ='{}'".format(email))
        emailDb = cursor.fetchall()
        print(emailDb)
        verificaEmail = False
        if not emailDb:
            verificaEmail = False
        else:
            verificaEmail = True
        if senha != senhaConf or email == "" or senha == "" or senhaConf == "":
            dlg = CustomDialog()
            dlg.exec()
            print("Senhas não batem ou campos em branco")
        elif verificaEmail == True:
            dlg = CustomDialogEqualEmail()
            dlg.exec()

        else:
            cursor = conn.cursor()
            cursor.execute("INSERT INTO cadastrados (email, senha) VALUES ('{}', '{}')".format(email, senha))

            conn.commit()
            conn.close()
            print("Email cadastrado com sucesso")
            dlg = CustomEmailCreated()
            dlg.exec()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 371)
        MainWindow.setStyleSheet("background-color: pink;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lb_email = QtWidgets.QLabel(self.centralwidget)
        self.lb_email.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.lb_email.setObjectName("lb_email")
        self.lb_senha = QtWidgets.QLabel(self.centralwidget)
        self.lb_senha.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.lb_senha.setObjectName("lb_senha")
        self.lb_senhaConf = QtWidgets.QLabel(self.centralwidget)
        self.lb_senhaConf.setGeometry(QtCore.QRect(40, 200, 81, 16))
        self.lb_senhaConf.setObjectName("lb_senhaConf")
        self.btn_Cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cadastrar.setGeometry(QtCore.QRect(100, 290, 111, 41))
        self.btn_Cadastrar.setStyleSheet("background-color: white;\n"
"border: 1px solid;")
        self.btn_Cadastrar.setObjectName("btn_Cadastrar")
        self.btn_Cadastrar.clicked.connect(self.cadastrando)


        self.edt_email = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_email.setGeometry(QtCore.QRect(40, 80, 221, 31))
        self.edt_email.setStyleSheet("background-color: white;")
        self.edt_email.setObjectName("edt_email")
        self.edt_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_senha.setGeometry(QtCore.QRect(42, 149, 221, 31))
        self.edt_senha.setStyleSheet("background-color: white;")
        self.edt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edt_senha.setObjectName("edt_senha")
        self.edt_senhaConf = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_senhaConf.setGeometry(QtCore.QRect(42, 229, 221, 31))
        self.edt_senhaConf.setStyleSheet("background-color: white;")
        self.edt_senhaConf.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edt_senhaConf.setObjectName("edt_senhaConf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastro"))
        self.lb_email.setText(_translate("MainWindow", "Email"))
        self.lb_senha.setText(_translate("MainWindow", "Senha"))
        self.lb_senhaConf.setText(_translate("MainWindow", "Confirmar senha"))
        self.btn_Cadastrar.setText(_translate("MainWindow", "Cadastrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CadastroWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

